import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  bookSidebar: [
    'index',
    'curriculum',
    'chapters/ch01-ai-infrastructure',
    'chapters/ch02-linux-process-files-observability',
    'chapters/ch03-networking',
    'chapters/ch04-performance-math',
    'chapters/ch05-gpu-cuda',
    'chapters/ch06-pytorch-execution',
    'chapters/ch07-numerical-precision',
    'chapters/ch08-distributed-collectives',
    'chapters/ch09-distributed-training',
    'chapters/ch10-training-ops',
    'chapters/ch11-data-systems',
    'chapters/ch12-evaluation',
    'chapters/ch13-artifact-management',
    'chapters/ch14-retrieval',
    'chapters/ch15-inference-execution',
    'chapters/ch16-model-serving-system',
    'chapters/ch17-kubernetes-gpu-orchestration',
    'chapters/ch18-ray-distributed-application-runtimes',
    'chapters/ch19-inference-optimization-accelerator-stack',
    'chapters/ch20-observability-debugging-incident-response',
    'chapters/ch21-ai-reliability-engineering',
    'chapters/ch22-ai-infra-security-privacy-supply-chain',
    'chapters/ch23-ai-infra-cost-capacity-energy-carbon',
    'chapters/ch24-platform-engineering',
    'chapters/ch25-ai-infra-frontiers',
    'chapters/ch26-end-to-end-ai-infra-capstone',
    'chapters/ch27-kv-transfer-and-connectors',
    'phase2/chapters/phase2-23-decoding-and-sampling',
    'phase2/chapters/phase2-26-kv-cache-and-paged-attention',
    'chapter-template',
    'lab-standards',
    'source-policy',
  ],
};

export default sidebars;
